//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Windows.Forms;

namespace EntityFraemworkPetProject.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MSSQLOnlineShopdbEntities : DbContext
    {
        public MSSQLOnlineShopdbEntities()
            : base("name=MSSQLOnlineShopdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }

        public void AddCustomer(Customer customer)
        {
            this.Customer.Add(customer);
            this.SaveChanges();
            MessageBox.Show($"Добавлен клиент {customer.Email}");
        }

        public void DeleteCustomer(Customer selectedCustomer)
        {
            DialogResult dialogResult = MessageBox.Show($"Точно хотите удалить {selectedCustomer.Email}?", "Удаление клиента", MessageBoxButtons.YesNo, MessageBoxIcon.Warning);
            if (dialogResult == DialogResult.Yes)
            {
                this.Customer.Remove(selectedCustomer);
                this.SaveChanges();
            }
        }

        public void AddOrder(Orders order)
        {
            this.Orders.Add(order);
            this.SaveChanges();
            MessageBox.Show($"Добавлен заказ {order.Email}");
        }

        public void DeleteOrder(Orders selectedOrder)
        {
            DialogResult dialogResult = MessageBox.Show($"Точно хотите удалить {selectedOrder.Id}?", "Удаление заказа", MessageBoxButtons.YesNo, MessageBoxIcon.Warning);
            if (dialogResult == DialogResult.Yes)
            {
                this.Orders.Remove(selectedOrder);
                this.SaveChanges();
            }
        }
    }
}
